//
//  File.swift
//  
//
//  Created by WolterS on 17/06/2023.
//

import Foundation


/// An error generated by the AutomowerConnect API.
public enum AutomowerConnectError: Error {
    /// A general error generated by an underlying function.
    /// - Parameter Error: The error generated
    case generalError(Error)
    /// A URL could not be generated from the given path
    /// - Parameter path: A String descirbing the requested path.
    case invalidURL(path: String)
    /// Did not get a valid callback after a Authorization Code Grant request.
    case receivedInvalidResponse
    /// Receveid a 401 status code after the request
    case badRequest
    /// Received a 403 status code after the request
    case unauthorized
    /// Receveid an invalid but inknown status code after the request
    case invalidStatusCode(Int)
    /// Cannot decode the received data to the requested type.
    /// - Parameter String: A string representation of the data received
    /// - Parameter Error: The error received from the decoder.
    case cannotDecode(String, Error)
    /// Cannot find the bundle with the credentials.json file.
    case cannotFindBundle
    /// Tried to use the API, but we are not looged in. The token is missing.
    case notLoggedIn
    
    
    var localizedDescription: String {
        switch self {
        case .generalError(let error): return "general error: \(error.localizedDescription)"
        case .invalidURL(path: let path): return "invalid URL for path \(path)"
        case .receivedInvalidResponse: return "received invalid response"
        case .badRequest: return "bad request"
        case .unauthorized: return "unauthorized"
        case .invalidStatusCode(let code): return "invalid status code \(code)"
        case .cannotDecode(let string, let error): return "cannot decode\n\(string)\n\(error.localizedDescription)"
        case .cannotFindBundle: return "cannot find bundle for credentials"
        case .notLoggedIn: return "not logged in. We do not have a token"
        }
    }
}
